// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package grpcs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Respones struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Respones) Reset()         { *m = Respones{} }
func (m *Respones) String() string { return proto.CompactTextString(m) }
func (*Respones) ProtoMessage()    {}
func (*Respones) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *Respones) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Respones.Unmarshal(m, b)
}
func (m *Respones) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Respones.Marshal(b, m, deterministic)
}
func (m *Respones) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Respones.Merge(m, src)
}
func (m *Respones) XXX_Size() int {
	return xxx_messageInfo_Respones.Size(m)
}
func (m *Respones) XXX_DiscardUnknown() {
	xxx_messageInfo_Respones.DiscardUnknown(m)
}

var xxx_messageInfo_Respones proto.InternalMessageInfo

func (m *Respones) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Request struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Respones)(nil), "grpcs.Respones")
	proto.RegisterType((*Request)(nil), "grpcs.Request")
}

func init() {
	proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c)
}

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0x2d, 0xac, 0x5f, 0x83, 0x5a, 0x0c, 0x08, 0x22, 0x28, 0xb2, 0x78, 0xf0, 0xb4, 0x42,
	0x15, 0x05, 0x6f, 0xb5, 0x87, 0x52, 0x8a, 0x5a, 0xb6, 0x16, 0xcf, 0xd3, 0xec, 0x74, 0x37, 0x90,
	0x26, 0x6b, 0x66, 0x96, 0xfe, 0x00, 0xff, 0xb8, 0xb0, 0x95, 0x7a, 0xf1, 0x90, 0xde, 0x12, 0xc2,
	0xf3, 0xbe, 0x79, 0x86, 0x81, 0x23, 0x6d, 0x0d, 0x39, 0xc9, 0xea, 0xe0, 0xc5, 0xab, 0xdd, 0x32,
	0xd4, 0x9a, 0xd3, 0x2b, 0x38, 0xc8, 0x89, 0x6b, 0xef, 0x88, 0x95, 0x82, 0xa4, 0x40, 0xc1, 0xf3,
	0xce, 0x75, 0xe7, 0xf6, 0x30, 0x6f, 0xcf, 0xe9, 0x25, 0xec, 0xe7, 0xf4, 0xd5, 0x10, 0xcb, 0x7f,
	0xcf, 0xbd, 0xef, 0x04, 0x92, 0x31, 0x2d, 0x1a, 0xf5, 0x04, 0x6a, 0x48, 0xf2, 0xee, 0xac, 0x71,
	0xd4, 0xb7, 0x36, 0xf7, 0x73, 0x2f, 0xac, 0x4e, 0xb2, 0xb6, 0x25, 0xfb, 0x8d, 0xb8, 0xe8, 0x6e,
	0xee, 0xeb, 0xca, 0x74, 0x47, 0xf5, 0xe0, 0x78, 0xe4, 0x98, 0x82, 0xbc, 0x12, 0x33, 0x96, 0x14,
	0xc9, 0x0c, 0xd0, 0x69, 0xb2, 0x5b, 0x30, 0xcf, 0x70, 0x36, 0x25, 0x0c, 0xba, 0x1a, 0x3b, 0xbf,
	0xb2, 0x54, 0x94, 0xf4, 0x61, 0xc4, 0x52, 0xd4, 0x1f, 0x1f, 0xa0, 0xfb, 0x27, 0x57, 0x2c, 0x8d,
	0x8b, 0xa2, 0x1e, 0xe1, 0x74, 0x6d, 0x36, 0x15, 0x14, 0xc3, 0x62, 0x34, 0xda, 0xc8, 0xb6, 0x49,
	0xc3, 0xd5, 0x1b, 0xad, 0x06, 0xde, 0x09, 0xea, 0xb8, 0x39, 0x8e, 0xe0, 0x66, 0x48, 0xb2, 0x91,
	0x7b, 0x41, 0xa6, 0x4f, 0x23, 0x55, 0x2b, 0xd9, 0x77, 0xc5, 0xc4, 0xa2, 0x2c, 0x7c, 0x58, 0xc6,
	0x44, 0xdd, 0x01, 0xcc, 0xea, 0x02, 0x85, 0x66, 0x4c, 0x21, 0x02, 0x98, 0xef, 0xb5, 0x2b, 0x75,
	0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xb4, 0xbf, 0x23, 0x62, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KefuClient is the client API for Kefu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KefuClient interface {
	GetOnlineAllRobots(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	InsertMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	CancelMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	SearchKnowledgeTitles(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	GetOnlineAdmins(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	InsertStatistical(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	PushNewContacts(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	GetKnowledgeBaseWithTitleAndPlatform(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
	UpdateUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error)
}

type kefuClient struct {
	cc grpc.ClientConnInterface
}

func NewKefuClient(cc grpc.ClientConnInterface) KefuClient {
	return &kefuClient{cc}
}

func (c *kefuClient) GetOnlineAllRobots(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/GetOnlineAllRobots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) InsertMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/InsertMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) CancelMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/CancelMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) SearchKnowledgeTitles(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/SearchKnowledgeTitles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) GetOnlineAdmins(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/GetOnlineAdmins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) InsertStatistical(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/InsertStatistical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) PushNewContacts(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/PushNewContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) GetKnowledgeBaseWithTitleAndPlatform(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/GetKnowledgeBaseWithTitleAndPlatform", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kefuClient) UpdateUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respones, error) {
	out := new(Respones)
	err := c.cc.Invoke(ctx, "/grpcs.Kefu/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KefuServer is the server API for Kefu service.
type KefuServer interface {
	GetOnlineAllRobots(context.Context, *Request) (*Respones, error)
	InsertMessage(context.Context, *Request) (*Respones, error)
	CancelMessage(context.Context, *Request) (*Respones, error)
	SearchKnowledgeTitles(context.Context, *Request) (*Respones, error)
	GetOnlineAdmins(context.Context, *Request) (*Respones, error)
	InsertStatistical(context.Context, *Request) (*Respones, error)
	PushNewContacts(context.Context, *Request) (*Respones, error)
	GetKnowledgeBaseWithTitleAndPlatform(context.Context, *Request) (*Respones, error)
	UpdateUser(context.Context, *Request) (*Respones, error)
}

// UnimplementedKefuServer can be embedded to have forward compatible implementations.
type UnimplementedKefuServer struct {
}

func (*UnimplementedKefuServer) GetOnlineAllRobots(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineAllRobots not implemented")
}
func (*UnimplementedKefuServer) InsertMessage(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertMessage not implemented")
}
func (*UnimplementedKefuServer) CancelMessage(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMessage not implemented")
}
func (*UnimplementedKefuServer) SearchKnowledgeTitles(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchKnowledgeTitles not implemented")
}
func (*UnimplementedKefuServer) GetOnlineAdmins(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineAdmins not implemented")
}
func (*UnimplementedKefuServer) InsertStatistical(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertStatistical not implemented")
}
func (*UnimplementedKefuServer) PushNewContacts(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushNewContacts not implemented")
}
func (*UnimplementedKefuServer) GetKnowledgeBaseWithTitleAndPlatform(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledgeBaseWithTitleAndPlatform not implemented")
}
func (*UnimplementedKefuServer) UpdateUser(ctx context.Context, req *Request) (*Respones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}

func RegisterKefuServer(s *grpc.Server, srv KefuServer) {
	s.RegisterService(&_Kefu_serviceDesc, srv)
}

func _Kefu_GetOnlineAllRobots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).GetOnlineAllRobots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/GetOnlineAllRobots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).GetOnlineAllRobots(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_InsertMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).InsertMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/InsertMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).InsertMessage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_CancelMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).CancelMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/CancelMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).CancelMessage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_SearchKnowledgeTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).SearchKnowledgeTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/SearchKnowledgeTitles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).SearchKnowledgeTitles(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_GetOnlineAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).GetOnlineAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/GetOnlineAdmins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).GetOnlineAdmins(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_InsertStatistical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).InsertStatistical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/InsertStatistical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).InsertStatistical(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_PushNewContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).PushNewContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/PushNewContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).PushNewContacts(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_GetKnowledgeBaseWithTitleAndPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).GetKnowledgeBaseWithTitleAndPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/GetKnowledgeBaseWithTitleAndPlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).GetKnowledgeBaseWithTitleAndPlatform(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kefu_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KefuServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Kefu/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KefuServer).UpdateUser(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kefu_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcs.Kefu",
	HandlerType: (*KefuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOnlineAllRobots",
			Handler:    _Kefu_GetOnlineAllRobots_Handler,
		},
		{
			MethodName: "InsertMessage",
			Handler:    _Kefu_InsertMessage_Handler,
		},
		{
			MethodName: "CancelMessage",
			Handler:    _Kefu_CancelMessage_Handler,
		},
		{
			MethodName: "SearchKnowledgeTitles",
			Handler:    _Kefu_SearchKnowledgeTitles_Handler,
		},
		{
			MethodName: "GetOnlineAdmins",
			Handler:    _Kefu_GetOnlineAdmins_Handler,
		},
		{
			MethodName: "InsertStatistical",
			Handler:    _Kefu_InsertStatistical_Handler,
		},
		{
			MethodName: "PushNewContacts",
			Handler:    _Kefu_PushNewContacts_Handler,
		},
		{
			MethodName: "GetKnowledgeBaseWithTitleAndPlatform",
			Handler:    _Kefu_GetKnowledgeBaseWithTitleAndPlatform_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Kefu_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
